### PR TITLE
Fix bug that stopped refresh token working

### PR DESCRIPTION
**Pull request by Jmz**
Make sure correct params are passed to the refresh token auth method.

### CODE REVIEW

**Comment by zot24** [comment]
`dev-develop` it's the latest version of the php-sdk the one that accounts and forge it's using, shouldnt this PR be made against develop branch instead?

**Comment by outrunthewolf** [comment]
This is bad.

That needs sorting. No one is going to remember these things, so its a good job you did. 

We should be using tags for anything consuming the SDK. We should remove dev-develop and just have develop and master.

**Comment by zot24** [comment]
oh with `dev-develop` i mean `develop` but on the composer file it will be reference as `dev-develop` orry my bad there is just master and develop

**Comment by Jmz** [comment]
Ok, so the plan is this:

- Merge this into master. 
- Tag a new stable 1.3 version. 
- Merge these fixes into develop.
- Tag a new dev 1.4 version while we work out whether changes in develop are breaking for people using older versions.

**Pull request merged**
